CREATE TABLE udon(name TEXT, price INT);
INSERT INTO udon VALUES('ВЈВ§В«Вс', 220);
INSERT INTO udon VALUES('ВЂВ¬ВЋВ§В«Вс', 320);
INSERT INTO udon VALUES('ВƒВсВ’ВзВ§В«Вс', 420);
INSERT INTO udon VALUES('ВіВйВ§В«Вс', 280);
INSERT INTO udon VALUES('ГJГМБ[В§В«Вс', 400);
INSERT INTO udon VALUES('В§В«ВсТиРH', 500);
SELECT * FROM udon;
SELECT * FROM udon WHERE price=20;
SELECT * FROM `udon` WHERE `price` <=430 ;
SELECT * FROM `udon` WHERE `price` IN(200,300.420);
SELECT * FROM `udon` WHERE`name`LIKE '%В§В«Вс' ;
SELECT * FROM `udon` WHERE`name`LIKE 'В§В«Вс%' ;
SELECT * FROM `udon` WHERE `name`LIKE '%В§В«Вс'AND`price`>=400 ;
SELECT * FROM `udon` WHERE`price`<300 OR `price`>400 ;
SELECT * FROM `udon`ORDER BY `price` ;
SELECT * FROM `udon` WHERE `price`>=300 ORDER BY `price` DESC ;
UPDATE udon SET name='ВљВ ВЂВ§В«Вс' WHERE name ='ВЂВ¬ВЋВ§В«Вс' ;
UPDATE udon SET price=price+920;
DELETE FROM udon WHERE price<=300;